# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

sudo: false

addons:
  apt:
    packages:
       # Requirements for Brian & NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    - python-tables 
    - libreadline6-dev 
    - libncurses5-dev 
    - libgsl0-dev

language: python

python: 2.7

virtualenv:
    system_site_packages: true
    
env:
    - OMV_ENGINE=PyNN_Nest
    - OMV_ENGINE=PyNN_NEURON

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - pwd
    - omv all -V
    
    
    
    

