# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation
# Still in development, subject to change without notice!!

language: python
python: 2.7

env:
    - OMV_ENGINE=PyNN_Brian1
    - OMV_ENGINE=PyNN_NEURON
    
virtualenv:
    system_site_packages: true
    
before_install:
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-sympy

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    
    
    
    

